version: "3"
services:
  app:
    build: .
    volumes: 
      - ./:/host_dir
    
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]